name: Node.js CI Workflow

# Define when this workflow should run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs (steps) that will run in the workflow
jobs:
  build:
    # This job will run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # The steps of the job
    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment (version 16)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install project dependencies using npm
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests using npm
      - name: Run tests
        run: npm test
